sonar.projectKey=trivy-cockpit-addon
sonar.projectName=Trivy Cockpit Addon
sonar.projectVersion=3.0.0
sonar.sources=.
sonar.exclusions=**/*.test.js,**/node_modules/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
