# SonarQube project configuration
sonar.projectKey=cockpit-trivy-scanner
sonar.projectName=Cockpit Trivy Scanner
sonar.projectVersion=1.0.0

# Path to source files
sonar.sources=.
sonar.exclusions=node_modules/**, reports/**, .git/**

# Encoding of the source code
sonar.sourceEncoding=UTF-8

# Languages
sonar.javascript.file.suffixes=.js
sonar.shell.file.suffixes=.sh
