sonar.projectKey=cockpit-trivy-addon
sonar.projectName=Trivy Security Dashboard for Cockpit
sonar.projectVersion=3.0.0
sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.exclusions=reports/**

# SonarQube server URL (can also be passed via -Dsonar.host.url or env var)
# sonar.host.url=http://localhost:9000
